services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=krishan123
      - MYSQL_DATABASE=appci_db
      - MYSQL_TCP_PORT=3307