name: Github Action demo
on: [push,workflow_dispatch]
jobs:
  Testing-the-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v2
      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
           node-version: 22

      - run: echo "The job is triggered by ${{github.event_name}}"

      - name: Installing Dependencies
        run: npm install
      # to lint the code
      - name: Linting the code
        run: npm run lint
      # to format the code
      - name: Formatting the code
        run: npm run format
      # to test the code
      - name: Running the test cases
        run: npm run test
    
