name: Github Action demo
on: [push,workflow_dispatch]
jobs:
  Testing-the-workflow:
    runs-on: macOS-latest
    steps:
      - run: echo "The job is triggered by ${{github.event_name}}"
      # to lint the code
      - run: npm run lint
      # to format the code
      - run: npm run format
      # to test the code
      - run: npm run test
    
